### ISSUE TITLE
怎么做实时的推理？

### ISSUE THREAD

**Issue by zuowanbushiwo** [sc0ttms/SE-DCCRN#1]
你好
       能上传推理部分的程序吗？ 我想使用的是的backup 的模型文件 对我的数据做处理可以吗？
谢谢！

**Comment by sc0ttms** [comment]
> 你好 能上传推理部分的程序吗？ 我想使用的是的backup 的模型文件 对我的数据做处理可以吗？ 谢谢！

@zuowanbushiwo 
推理部分在 `inferencer/base_inferencer.py`
你可以通过修改上述文件中的`test_iter`获取需要前向推理的数据集即可

**Comment by zuowanbushiwo** [comment]
你好，非常感谢回复，但我还是有些不理解。 
1.我下载你了的[dns_interspeech_2021_mandarin_1h.zip](https://aistudio.baidu.com/aistudio/datasetdetail/118354), 再执行了 `unzip.py`  `gen.py`  python文件，在根目录上生成了dataset_csv 文件夹，里面的 `test.csv` 文件中包含了11个音频文件的路径。
2. 修改` config/base_config.toml `文件 中`path `部分，修改如下：
```
[path]
base = "./output/dccrn"
# base = "/model/dccrn"
# pre_model = 0
pre_model = "./backup/base_model.pth"
```
3.  执行 `python inferencer/base_inferencer.py  -C ./config/base_config.toml`

得到如下错误：
```
cuda
number of test files 10
Contains 1 models, the number of the parameters is:
        Network 1: 3.671053 million.
The amount of parameters in the project is 3.671053 million.
Load pre model done...
inference:   0%|   
RuntimeError: CUDA out of memory. Tried to allocate 626.00 MiB (GPU 0; 10.76 GiB total capacity; 4.40 GiB already allocated; 565.44 MiB free; 4.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
是要修改`batch_size` 参数吗？ 这个应该怎么改？能指导一下吗？

我有几个疑问：
1.   `base_trainer.py` 使用  `base_config.toml` 训练出 `base_model.pth` 吗？
2.   `knowledge_distillation_trainer.py `使用 `lite_v1_config.toml` 训练出  `lite_v1_model.pth` 吗？
3.  `lite_v1d_model.pth` 是哪个trainer 训练出来的？我看大小是`lite_v1_model.pth `一样，也是和上面一样的吗？
4.  `prune_trainer.py` 和  `quantization_trainer.py`  使用哪个config 文件？它们没有训练出模型文件吗？
5.  关于推理时，我可以使用 `lite_v1_model.pth`  吗？ 也是像上面一样 `python inferencer/base_inferencer.py  -C ./config/base_config.toml`，只是把 `base_config.toml `中` [path][pre_model] =  ./backup/lite_v1_model.pth `  修改就可以了，还是需要换成 `lite_v1_config.toml` 文件

不好意思，问题比多，我是刚刚入门AI 降噪，想找一个比较完整的开源项目跑一边，这样学习快一些，你这个项目有训练好的模型，也有一个比较好的优化点，值得好好学习。

谢谢！

**Comment by zuowanbushiwo** [comment]
@sc0ttms 
上面的报错 我修改 `  base_config.toml `后 ，修改如下，然后再 执行  `python inferencer/base_inferencer.py -C ./config/base_config.toml`
```
[dataloader]
batch_size = [3, 2]
```

得到的结果：
```
,SI_SDR,STOI,WB_PESQ,NB_PESQ
test,6.9936803644523025,0.7949074699286751,1.4987192749977112,2.1684714674949648
```

```
,SI_SDR,STOI,WB_PESQ,NB_PESQ
enh,15.97127217054367,0.8864858691614532,2.83180810213089,3.222379183769226
```

**Comment by sc0ttms** [comment]
==>是要修改batch_size 参数吗？ 这个应该怎么改？能指导一下吗？
你理解的是对的，内存不足引起的报错，减少batch_size即可，我当时训练的设备是32GB的缓存

关于后面的几个问题
问题1，是的
问题2/3，是蒸馏的结果，但是并不是特别理想，你可以根据蒸馏的论文对代码做些修改，看看有没有更好的效果
问题4，关于模型压缩的一些训练，目前工作事情相对比较多，空余时间会对模型压缩训练做更新，包括剪枝/蒸馏/量化，目前的代码并不是一个可供学习的参考，正确性仍需要验证，欢迎讨论
问题5，需要更换成lite_v1_config.toml 比如蒸馏压缩后模型的结构发生了变化

**Comment by sc0ttms** [comment]
@zuowanbushiwo 
获得的结果是符合预期的，summary中是100小时数据集的均值

**Comment by zuowanbushiwo** [comment]
@sc0ttms 
非常感谢大佬的回答，会一直关注你的更新的，我也会努力学习，争取早点入门。
目前整个推理流程基本跑完，得到如下结果：
```
,SI_SDR,STOI,WB_PESQ,NB_PESQ
test,6.9936803644523025,0.7949074699286751,1.4987192749977112,2.1684714674949648

lite_v1d_model：
,SI_SDR,STOI,WB_PESQ,NB_PESQ
enh,15.03709614276886,0.8710123734227944,2.5492427349090576,3.0315118074417113

lite_v1_model：
,SI_SDR,STOI,WB_PESQ,NB_PESQ
enh,15.002033293247223,0.8706388663211702,2.539791929721832,3.020973014831543

base_model：
,SI_SDR,STOI,WB_PESQ,NB_PESQ
enh,15.97127217054367,0.8864858691614532,2.83180810213089,3.222379183769226
```

(1) 剪枝/蒸馏/量化 压缩后的模型还能onnx导出吗？能在手机上部署实时运行吗？上周查资料发现目前很多都是pytorch->onnx(pnnx)->ncnn 这样的部署方式。
(2) 还有这个模型是不是很难训练啊？你100h的数据训练用了多长时间？
(3) 这个蒸馏后模型的效果比DTLN, RNNoise 要好吗？目前就只看过这两个项目。

难得碰到有耐心的大佬，问题比较多，还请理解。
祝身体健康，家庭幸福，工作顺利。

**Comment by sc0ttms** [comment]
1. 部署部分我也刚接触，你提到的方式应该是可行的，或者采用TVM也可以
2. 这个模型很好训练，100h的数据使用V100 32G单卡，训练20多个小时就有结果了
3. 蒸馏后的效果取决于蒸馏后的模型大小，如果压缩很多，需要评估性能下降了多少，backup中的模型压缩不大，性能损失不明显

我也是刚接触这部分内容，不是什么大佬，有问题可以多沟通交流

**Comment by zuowanbushiwo** [comment]
好的，非常感谢您耐心回答，已经解决我很多问题了。
祝身体健康，家庭幸福，工作顺利。
